#!/usr/bin/env sh

# download and install docker
sudo apt install docker.io

# launch docker
# sudo systemctl enable --now docker

# disable docker
# sudo systemctl disable --now docker

# check docker version
docker --version

# set user privileges
sudo chmod 666 /var/run/docker.sock
sudo usermod -aG docker $USER

# test docker
docker run hello-world
